# Generated by Django 2.2 on 2022-09-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warden',
            old_name='Block_Name',
            new_name='Hostel_Name',
        ),
        migrations.RenameField(
            model_name='warden',
            old_name='Floor_Number',
            new_name='Hostel_Number',
        ),
    ]
