# Generated by Django 2.2 on 2022-09-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_auto_20220915_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warden',
            old_name='Hostel_Name',
            new_name='Hostel_Names',
        ),
        migrations.RenameField(
            model_name='warden',
            old_name='Hostel_Number',
            new_name='Hostel_Numbers',
        ),
    ]
