# Generated by Django 2.2 on 2022-09-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_auto_20220915_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warden',
            old_name='Hostel_Names',
            new_name='Hostel_Name',
        ),
        migrations.RenameField(
            model_name='warden',
            old_name='Hostel_Numbers',
            new_name='Hostel_Number',
        ),
    ]
