# Generated by Django 2.2 on 2022-09-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_auto_20220915_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='floors',
            name='Capacity',
            field=models.IntegerField(default=4),
        ),
    ]
